/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** AAI.hpp
*/

#ifndef OOP_ARCADE_2019_SYSTEM_AAI_HPP
#define OOP_ARCADE_2019_SYSTEM_AAI_HPP

#endif // OOP_ARCADE_2019_SYSTEM_AAI_HPP
