/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** ARender.hpp
*/

#ifndef OOP_ARCADE_2019_SYSTEM_ARENDER_HPP
#define OOP_ARCADE_2019_SYSTEM_ARENDER_HPP

#endif // OOP_ARCADE_2019_SYSTEM_ARENDER_HPP
