/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** AUser.hpp
*/

#ifndef OOP_ARCADE_2019_SYSTEM_AUSER_HPP
#define OOP_ARCADE_2019_SYSTEM_AUSER_HPP

#endif // OOP_ARCADE_2019_SYSTEM_AUSER_HPP
