/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** Physics.hpp
*/

#ifndef OOP_ARCADE_2019_SYSTEM_PHYSICS_HPP
#define OOP_ARCADE_2019_SYSTEM_PHYSICS_HPP

#endif // OOP_ARCADE_2019_SYSTEM_PHYSICS_HPP
