/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** EventBus.hpp
*/

#ifndef OOP_ARCADE_2019_EVENTBUS_EVENTBUS_HPP
#define OOP_ARCADE_2019_EVENTBUS_EVENTBUS_HPP

#endif // OOP_ARCADE_2019_EVENTBUS_EVENTBUS_HPP
