/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** IEvent.hpp
*/

#ifndef OOP_ARCADE_2019_EVENTBUS_IEVENT_HPP
#define OOP_ARCADE_2019_EVENTBUS_IEVENT_HPP

#endif // OOP_ARCADE_2019_EVENTBUS_IEVENT_HPP
