/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** AAudio.hpp
*/

#ifndef OOP_ARCADE_2019_COMPONENT_AAUDIO_HPP
#define OOP_ARCADE_2019_COMPONENT_AAUDIO_HPP

#endif // OOP_ARCADE_2019_COMPONENT_AAUDIO_HPP
