/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** Animations.hpp
*/

#ifndef OOP_ARCADE_2019_COMPONENT_ANIMATIONS_HPP
#define OOP_ARCADE_2019_COMPONENT_ANIMATIONS_HPP

#endif // OOP_ARCADE_2019_COMPONENT_ANIMATIONS_HPP
