/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** Hitbox.hpp
*/

#ifndef OOP_ARCADE_2019_COMPONENT_HITBOX_HPP
#define OOP_ARCADE_2019_COMPONENT_HITBOX_HPP

#endif // OOP_ARCADE_2019_COMPONENT_HITBOX_HPP
