/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** Size.hpp
*/

#ifndef OOP_ARCADE_2019_COMPONENT_SIZE_HPP
#define OOP_ARCADE_2019_COMPONENT_SIZE_HPP

#endif // OOP_ARCADE_2019_COMPONENT_SIZE_HPP
