/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** ASystem.hpp
*/

#ifndef OOP_ARCADE_2019_ECS_ASYSTEM_HPP
#define OOP_ARCADE_2019_ECS_ASYSTEM_HPP

#endif // OOP_ARCADE_2019_ECS_ASYSTEM_HPP
