/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** IComponent.hpp
*/

#ifndef OOP_ARCADE_2019_ECS_ICOMPONENT_HPP
#define OOP_ARCADE_2019_ECS_ICOMPONENT_HPP

#endif // OOP_ARCADE_2019_ECS_ICOMPONENT_HPP
