/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** ISystem.hpp
*/

#ifndef OOP_ARCADE_2019_ECS_ISYSTEM_HPP
#define OOP_ARCADE_2019_ECS_ISYSTEM_HPP

#endif // OOP_ARCADE_2019_ECS_ISYSTEM_HPP
