/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** Universe.hpp
*/

#ifndef OOP_ARCADE_2019_ECS_UNIVERSE_HPP
#define OOP_ARCADE_2019_ECS_UNIVERSE_HPP

#endif // OOP_ARCADE_2019_ECS_UNIVERSE_HPP
