/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** Collision.hpp
*/

#ifndef OOP_ARCADE_2019_EVENT_COLLISION_HPP
#define OOP_ARCADE_2019_EVENT_COLLISION_HPP

#endif // OOP_ARCADE_2019_EVENT_COLLISION_HPP
