/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** Input.hpp
*/

#ifndef OOP_ARCADE_2019_EVENT_INPUT_HPP
#define OOP_ARCADE_2019_EVENT_INPUT_HPP

#endif // OOP_ARCADE_2019_EVENT_INPUT_HPP
