/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** Action.hpp
*/

#ifndef OOP_ARCADE_2019_SRC_GAME_EMULATOR_COMPONENT_ACTION_HPP
#define OOP_ARCADE_2019_SRC_GAME_EMULATOR_COMPONENT_ACTION_HPP

#endif // OOP_ARCADE_2019_SRC_GAME_EMULATOR_COMPONENT_ACTION_HPP
