/*
** EPITECH PROJECT, 2020
** OOP_arcade_2019
** File description:
** User.hpp
*/

#ifndef OOP_ARCADE_2019_SRC_GAME_EMULATOR_COMPONENT_USER_HPP
#define OOP_ARCADE_2019_SRC_GAME_EMULATOR_COMPONENT_USER_HPP

#endif // OOP_ARCADE_2019_SRC_GAME_EMULATOR_COMPONENT_USER_HPP
